'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4206
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Operation_Overlord.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _38411863un3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("38411863un3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _58673378wi4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("58673378wi4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AC130___105mm_sound_effect_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AC130___105mm_sound_effect_", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Animation1__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Animation1__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Artillery() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Artillery", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property B_26_Marauder_drops_a_string_of_100_pound_bombs_over_France() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B-26 Marauder drops a string of 100-pound bombs over France", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property casualties1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("casualties1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Concept_Art() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Concept Art", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Firing_the_88mm_flak_gun() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Firing_the_88mm_flak_gun", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Firing_the_88mm_flak_gun_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Firing_the_88mm_flak_gun_1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Form_3_Music_3_2_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Form_3_Music_3_2_1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Form_4_Go_Go_Go() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Form_4_Go_Go_Go", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Form_5_Off_the_boat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Form_5_Off_the_boat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Heavy_Mounted_Machine_Gun() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Heavy_Mounted_Machine_Gun", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Martin_Marauder_in_Action() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Martin_Marauder_in_Action", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Martin_Marauder_in_Action1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Martin_Marauder_in_Action1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Naval_Bombardment_of_Iwo_Jima() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Naval_Bombardment_of_Iwo_Jima", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property nevada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nevada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nijmegenbridgenorthundexm7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nijmegenbridgenorthundexm7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Off_the_boat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Off_the_boat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property relic00000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic000001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic000001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic000151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic000151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00124() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00124", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00131() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00131", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00139() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00139", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00149() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00149", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00156() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00156", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00165() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00165", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00167() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00167", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relic00182() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relic00182", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property semperfi_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("semperfi_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Taps() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Taps", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
